### ISSUE TITLE
Only 3 random colors generated in plot

### ISSUE THREAD

**Issue by DanielRichardBiber** [frankkramer-lab/mully#5]
Seems like only 3 colors are generated at random.  This is prohibitive in graphs that have over 3 layers.  In addition, it would be great if we could customize the palate (rColorBrewer).

I'm not sure there is an override available to users as the colors are generated inside the plot.mully function.  But I am new to R so I could be mistaken.

**Comment by zaynabhammoud** [comment]
Hi!
Thank you for your comment and sorry for replying so late. I will rewrite the plotting function so it would be controlled by users, but I am not sure about the three colors; the colors are generated randomly using randomColor, then assigned to the layers. I already have a graph containing 4 layers with four different colors. Could you please check if you have more than three layers? It would also be nice if you could pass the code so I could check it.

**Comment by DanielRichardBiber** [comment]
Thanks for the reply.

I am quite sure I have more than 3 layers.  The error seemed odd to me but I have yet to be able to overcome it.  

Here is the image for the code below.
![RMullyPlotFinal01](https://user-images.githubusercontent.com/43456796/57054428-94c45380-6c62-11e9-81f7-381af2db39b2.png)

Here are my layers
> print(g)
mully --  InfoVisProject
 7 Layers:
  ID               Name          NameLower
 1  1               gene               gene
 2  2        bio process        bio process
 3  3     cell component     cell component
 4  4          phenotype          phenotype
 5  5 molecular function molecular function
 6  6    target darkness    target darkness
 7  7      target family      target family



library(mully)
library(igraph)
setwd("~/GVSU/CIS 671 - Info Viz/Project3")

g <- mully("InfoVisProject",direct = F) 
g <- addLayer(g, c("gene", "bio process", "cell component", "phenotype", "molecular function", "target darkness", "target family"))

print(g)

noderaw = read.csv("export11thinnodelc.csv", header = TRUE)
edgeraw = read.csv("export11thinedgelc.csv", header = TRUE)

print(g)

for(i in 1:nrow(noderaw)){
  g=addNode(g,paste0(noderaw[i,1]),paste0(noderaw[i,2]))
  
}
print(g)
print(getNodeAttributes(g))

for (i in 1:nrow(edgeraw)){
  g=addEdge(g,paste0(edgeraw[i,1]),paste0(edgeraw[i,2]),list(name=paste0(edgeraw[i,4])))  
}

#variable for the Margins
marginint = -0.1

#Set the Margins to a larger size
graph_attr(g, "margin") <- c(marginint,marginint,marginint,marginint)

#Set Aspect Ratio to wider (its locked)
graph_attr(g, "asp") <- 0.55

#find the degree of the graph
deg <- degree(g, mode="all")

n <- length(deg)

#Set background color to grey
par(bg="grey95")

#Set Node Size to degree and the variables
degreemulty = 0.3
degreeplus = 4
degreefactorr = degreeplus+(deg*degreemulty) 
V(g)$size <- degreefactorr

#Set extra Layers to color white
V(g)$color <- "white"

#Set Edge color
E(g)$color <- "gray80"

#Set label size
V(g)$label.cex <- 0.9

#Set label distance
V(g)$label.dist <- c(1,2)

#Set Label Position
V(g)$label.degree <- pi/2

#set Edge curavature
curve_multiple(g,start = 0.5)
edge.curved=TRUE

#Actually plot the graph
plot(g,layout = "scaled")


#Attempt to set color, as its in the function "plot" it gets overrode
colrs <- c("gray50", "tomato", "gold", "red", "blue", "yellow")
V(g)$color <- colrs
plot.igraph(g,mark.groups = list(),edge.curved=0.2, vertex.color=colrs)
V(g)$label.dist <- 0.5
tkplot(g,edge.curved=0.2)
rglplot(g)
plot3d(g)

**Comment by zaynabhammoud** [comment]
Hi again,
I fixed the problem. It was actually a silly one :D I also modified it so you could keep your own colors. Please test it and tell me.

**Comment by DanielRichardBiber** [comment]
Thanks for taking time on updating this.  I reinstalled Mully and the issue
is still occuring with the code I provided earlier on Github.

Did I potentially miss something?

Dan Biber

**Comment by zaynabhammoud** [comment]
Could you please send me your nodes and edges lists?

**Comment by DanielRichardBiber** [comment]
Let me know if you need anything else :)

**Comment by zaynabhammoud** [comment]
Sorry didn't receive anything. Could you please send them to my email: zaynabhassanhammoud@gmail.com?

**Comment by zaynabhammoud** [comment]
Hi again,
So since I didn't receive your lists, I created the graph myself without the edges, and visualized it. That was the result.

![Rplot](https://user-images.githubusercontent.com/19550037/58255525-74714b80-7d6d-11e9-8718-c34883042e1a.png)

Could you please recheck that you have the newest version of mully?

Zaynab
